var http = require('http');

http.createServer(function (request, response) {
	response.writeHead(200, {"Content-Type": "text/html"}); 
	response.write("<!DOCTYPE html>");
response.write("<html>");
response.write("<head>");
response.write("	<meta charset=\"utf-8\" />");
response.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
response.write("	<title>Книги на Агата Кристи</title>");
response.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css\" />");
response.write("</head>");
response.write("<header><div class=\"container\"><h1 class=\"lead\">Агата Кристи</h1></div></header>");
response.write("<div class=\"container\">");
response.write("	<dt>Романи</dt>");
response.write("	<dd><s class=\"text-muted\">1920 „Аферата в Стайлс“ – The Mysterious Affair at Styles (дебют на Еркюл Поаро)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1922 „Тайният противник“ – The Secret Adversary (дебют на Томи и Тапънс)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1923 „Убийство на игрището за голф“ – The Murder on the Links</s></dd>");
response.write("	<dd><s class=\"text-muted\">1924 „Мъжът с кафявия костюм“ – The Man in the Brown Suit (дебют на полковник Рейс)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1925 „Тайната на имението“ – The Secret of Chimneys (дебют на старши инспектор/комисар Батъл)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1926 „Алиби“/“Убийството на Роджър Акройд“ – The Murder of Roger Ackroyd</s></dd>");
response.write("	<dd><s class=\"text-muted\">1927 „Великата четворка“ – The Big Four</s></dd>");
response.write("	<dd><s class=\"text-muted\">1928 „Мистерията в „Синия експрес“ – The Mystery of the Blue Train</s></dd>");
response.write("	<dd><s class=\"text-muted\">1929 „Седемте циферблата“ – The Seven Dials Mystery</s></dd>");
response.write("	<dd><s class=\"text-muted\">1930 „Убийство в дома на свещеника“ – The Murder at the Vicarage (романен дебют на г-ца Марпъл)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1931 „Загадката от Ситафорд“ – The Sittaford Mystery (известен и под заглавието The Murder at Hazelmoor)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1932 „Загадката на Енд Хаус“ – Peril at End House</s></dd>");
response.write("	<dd><s class=\"text-muted\">1933 „Смъртта на лорд Еджуеър“ – Lord Edgware Dies (известен и под заглавието 13 at Dinner)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1934 „Убийство в Ориент Експрес“ – Murder on the Orient Express (известен и под заглавието Murder in the Calais Coach)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1934 „Защо не повикаха Евънс?“ – Why Didn't They Ask Evans? (известен и под заглавието The Boomerang Clue)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1934 „Трагедия в три действия“ – Three Act Tragedy (известен и под заглавието Murder in Three Acts)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1935 „Смърт в облаците“ – Death in the Clouds (известен и под заглавието Death in the Air)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1936 „Азбучни убийства“ – The A.B.C. Murders</s></dd>");
response.write("	<dd><s class=\"text-muted\">1936 „Убийство в Месопотамия“ – Murder in Mesopotamia</s></dd>");
response.write("	<dd><s class=\"text-muted\">1936 „Карти на масата“ – Cards on the Table (романен дебют на Ариадни Оливър)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1937 „Безмълвният свидетел“ – Dumb Witness (известен и под заглавието Poirot Loses a Client)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1937 „Смърт край Нил“ – Death on the Nile</s></dd>");
response.write("	<dd><s class=\"text-muted\">1938 „Среща със смъртта“ – Appointment with Death</s></dd>");
response.write("	<dd><s class=\"text-muted\">1938 „Убийство по Коледа“/“Коледата на Поаро“ – Hercule Poirot's Christmas (известен и под заглавието Murder for Christmas)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1939 „Да се убива е лесно“ – Murder is Easy (известен и под заглавието Easy to Kill)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1939 „Десет малки негърчета“ – And Then There Were None (първоначално известен и под заглавието Ten Little Niggers)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1940 „Загърни ме в мрачен покров“/“Тъжният кипарис“ – Sad Cypress</s></dd>");
response.write("	<dd><s class=\"text-muted\">1940 „Смъртта на господин Морли“ – One, Two, Buckle My Shoe (известен и под заглавието The Patriotic Murders)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1941 „Зло под слънцето“ – Evil Under the Sun</s></dd>");
response.write("	<dd><s class=\"text-muted\">1941 „Произшествие в „Сан Суси“/“N или M?“ – N or M?</s></dd>");
response.write("	<dd><s class=\"text-muted\">1942 „Трупът в библиотеката“ – The Body in the Library</s></dd>");
response.write("	<dd><s class=\"text-muted\">1942 „Пет малки прасенца“ – Five Little Pigs (известен и под заглавието Murder in Retrospect)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1942 „Смърт в Лимсток“/“Анонимният подател“ – The Moving Finger</s></dd>");
response.write("	<dd><s class=\"text-muted\">1944 „Нула часът- развръзката“ – Towards Zero (последна поява на комисар Батъл)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1944 „Накрая идва смъртта“ – Death Comes as the End</s></dd>");
response.write("	<dd><s class=\"text-muted\">1945 „Искрящ цианкалий“ – Sparkling Cyanide (известен и под заглавието Remembered Death) (последна поява на полковник Рейс)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1946 „Имението Холоу“ – The Hollow</s></dd>");
response.write("	<dd><s class=\"text-muted\">1948 „Фатален шанс“ – Taken at the Flood (известен и под заглавието There is a Tide...)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1949 „Чудноватият дом“ – Crooked House</s></dd>");
response.write("	<dd><s class=\"text-muted\">1950 „Предизвестено убийство“ – A Murder is Announced</s></dd>");
response.write("	<dd><s class=\"text-muted\">1951 „Среща в Багдад“ – They Came to Baghdad</s></dd>");
response.write("	<dd><s class=\"text-muted\">1952 „Смъртта на госпожа Макгинти“ – Mrs McGinty's Dead</s></dd>");
response.write("	<dd><s class=\"text-muted\">1952 „Илюзия с огледала“ – They Do It with Mirrors (известен и под заглавието Murder with Mirrors)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1953 „След погребението“ – After the Funeral (известен и под заглавието Funerals Are Fatal)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1953 „Джоб, пълен с ръж“ – A Pocket Full of Rye</s></dd>");
response.write("	<dd><s class=\"text-muted\">1954 „Направление неизвестно“ – Destination Unknown (известен и под заглавието So Many Steps to Death)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1955 „Хикъри Дикъри Док“ – Hickory Dickory Dock (известен и под заглавието Hickory Dickory Death)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1956 „Двойно убийство“ – Dead Man's Folly</s></dd>");
response.write("	<dd>1957 „16:50 от Падингтън“ – 4.50 from Paddington (известен и под заглавието What Mrs. McGillycuddy Saw!)</dd>");
response.write("	<dd><s class=\"text-muted\">1958 „Изпитание за невинните“ – Ordeal by Innocence</s></dd>");
response.write("	<dd><s class=\"text-muted\">1959 „Котка сред гълъбите“ – Cat Among the Pigeons</s></dd>");
response.write("	<dd><s class=\"text-muted\">1961 „Сивият кон“ – The Pale Horse</s></dd>");
response.write("	<dd><s class=\"text-muted\">1962 „Проклятието на огледалото“ – The Mirror Crack'd from Side to Side (известен и под заглавието The Mirror Crack'd)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1963 „Часовниците“ – The Clocks</s></dd>");
response.write("	<dd><s class=\"text-muted\">1964 „Карибска мистерия“ – A Caribbean Mystery</s></dd>");
response.write("	<dd><s class=\"text-muted\">1965 „В хотел Бъртрам“ – At Bertram's Hotel</s></dd>");
response.write("	<dd><s class=\"text-muted\">1966 „Третото момиче“ – Third Girl</s></dd>");
response.write("	<dd><s class=\"text-muted\">1967 „Безкрайна нощ“ – Endless Night</s></dd>");
response.write("	<dd><s class=\"text-muted\">1968 „Злото е на път“ – By the Pricking of My Thumbs</s></dd>");
response.write("	<dd><s class=\"text-muted\">1969 „Празникът на Вси Светии“ – Hallowe'en Party</s></dd>");
response.write("	<dd><s class=\"text-muted\">1970 „Пътник за Франкфурт“ – Passenger to Frankfurt</s></dd>");
response.write("	<dd><s class=\"text-muted\">1971 „Възмездието“ – Nemesis</s></dd>");
response.write("	<dd><s class=\"text-muted\">1972 „Слоновете помнят“ – Elephants Can Remember (последна поява на Ариадни Оливър)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1973 „Задната врата на съдбата“ – Postern of Fate (последният роман, написан от Агата Кристи; последна поява на Томи и Тапънс)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1975 „Завесата: Последният случай на Поаро“ – Curtain: Poirot's Last Case (написан около 30 години по-рано)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1976 „Стаена смърт“ – Sleeping Murder (последният случай с г-ца Марпъл, написан около 30 години по-рано)</s></dd>");
response.write("	<dt>Сборници с разкази</dt>");
response.write("	<dd>1924 „Поаро разследва“ – Poirot Investigates (11 разказа с Еркюл Поаро; 14 в американското издание)</dd>");
response.write("	<dd><s class=\"text-muted\">929 „Съдружници срещу престъплението“ – Partners in Crime (14 разказа с Томи и Тапънс)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1930 „Загадъчният господин Куин“ – The Mysterious Mr. Quin (12 разказа с Харли Куин)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1932 „Клуб вторник вечер“ – The Thirteen Problems (известен и под заглавието The Tuesday Club Murders) (13 разказа с г-ца Марпъл)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1933 „Чудовището на смъртта“/“Кучето на ада“- The Hound of Death (12 разказа; публикуван само във Великобритания)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1934 „Загадката на Листърдейл“ – The Listerdale Mystery (12 разказа; публикуван само във Великобритания)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1934 „Случаите на Паркър Пайн“ – Parker Pyne Investigates (известен и под заглавието Mr. Parker Pyne, Detective) (12 разказа с Паркър Пайн)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1937 „Невероятната кражба и други истории“ – Murder in the Mews (известен и под заглавието Dead Man's Mirror) (4 повести с Еркюл Поаро)</s></dd>");
response.write("	<dd>1939 „Мистерия с диамант и други разкази“ – The Regatta Mystery and Other Stories (9 разказа; публикуван само в САЩ)</dd>");
response.write("	<dd>1947 „Подвизите на Еркюл“ – The Labours of Hercules (12 разказа с Еркюл Поаро)</dd>");
response.write("	<dd><s class=\"text-muted\">1948 „Свидетел на обвинението и други разкази“ – The Witness for the Prosecution and Other Stories (11 разказа; публикуван само в САЩ)</s></dd>");
response.write("	<dd><s class=\"text-muted\">1950 „Три слепи мишлета и други разкази“ – Three Blind Mice and Other Stories (9 разказа; публикуван само в САЩ)</s></dd>");
response.write("	<dd>1951 The Under Dog and Other Stories (9 разказа с Еркюл Поаро; публикуван само в САЩ)</dd>");
response.write("	<dd><s class=\"text-muted\">1960 „Приключението на коледния пудинг“ – The Adventure of the Christmas Pudding (6 разказа; публикуван само във Великобритания)</s></dd>");
response.write("	<dd>1961 Double Sin and Other Stories (8 разказа; публикуван само в САЩ)</dd>");
response.write("	<dd>1971 The Golden Ball and Other Stories (15 разказа; публикуван само в САЩ)</dd>");
response.write("	<dd>1974 „Ранните случаи на Поаро“ – Poirot's Early Cases (18 разказа с Еркюл Поаро)</dd>");
response.write("	<dd>1979 „Куклата на шивачката“ – Miss Marple's Final Cases and Two Other Stories (8 разказа; публикуван само във Великобритания)</dd>");
response.write("	<dd>1991 Problem at Pollensa Bay and Other Stories (8 разказа; публикуван само във Великобритания)</dd>");
response.write("	<dd>1997 The Harlequin Tea Set (9 разказа; публикуван само в САЩ)</dd>");
response.write("	<dd>1997 While the Light Lasts and Other Stories (9 разказа; публикуван само във Великобритания)</dd>");
response.write("	<dt>Постановки/Книги</dt>");
response.write("	<dd>1998 „Черно кафе“ – Black Coffee</dd>");
response.write("	<dd><s class=\"text-muted\">1999 „Неочакваният гост“ – The Unexpected Guest</s></dd>");
response.write("	<dd>2000 „Паяжината“ – Spider's Web</dd>");
response.write("</div>");
response.write("<footer><blockquote><p class=\"text-right\">mfb 2017</p></blockquote></footer>");
response.write("<body>");
response.write("</body>");
response.write("</html>");
	response.end();
}).listen(process.env.PORT || 8080);